name: crypto-unified
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas=2.0.3
  - numpy=1.24.4
  - scipy=1.10.1
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.15.0
  - pymongo=4.3.3
  - requests=2.31.0
  - pytest=7.4.0
  - pip
  - pip:
    - psycopg2-binary==2.9.6
    - pymysql==1.1.0
    - kafka-python==2.0.2
    - confluent-kafka==2.1.1
    - pyspark==3.3.2
    - findspark==2.0.1
    - py4j==0.10.9.5
    - dash==2.11.1
    - python-dotenv==1.0.0
    - pyarrow==12.0.1
    - fastavro==1.7.3
    - avro==1.11.1
    - pytest-mock==3.11.1
    - loguru==0.7.0
    - ccxt
    - apache-airflow==2.6.3
    - apache-airflow-providers-apache-spark==4.0.0
    - apache-airflow-providers-apache-kafka==1.0.0
    - apache-airflow-providers-postgres==5.6.0
    - apache-airflow-providers-sqlite==3.4.3
    - apache-airflow-providers-http==4.5.0
    - apache-airflow-providers-common-sql==1.7.1
    - kaleido==0.2.1
    - pendulum==2.1.2
    - tenacity==8.2.2
    - attrs==23.1.0
    - streamlit==1.22.0